### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by Avolon** [ztmzzz/CHITUBOXPro-trial#1]
Hello!
After updating the site Chitoubok registration automatically does not work (
`Traceback (most recent call last):
  File "E:\CHITUBOXPro-trial-main\main.py", line 136, in <module>
    (email, password) = register()
  File "E:\CHITUBOXPro-trial-main\main.py", line 38, in register
    email = driver.find_element(By.XPATH,
  File "*****AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "******AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "********AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/app-root/app-layout/div/section/div/div/app-register/div/div[2]/div[1]/form/div[1]/div/input"}
  (Session info: chrome=106.0.5249.121)`

Google Chrome  106!

**Comment by ztmzzz** [comment]
Thank you! I will deal with it tonight.
